---
title: MoMa Data
---

```{r setup, include = FALSE}
# Load shiny
library(shiny)
# Load tidyverse
library(tidyverse)
# Define empty server functi
server <- function(input, output, session) {

}
if (requireNamespace('rstudioapi', quietly = TRUE)){
  options(shiny.launch.browser = rstudioapi::viewer)
}
```


## Artworks

```{r}
artworks <- readr::read_csv('../data/Artworks.csv') %>% 
  janitor::clean_names()
artworks
```

### Artworks Acquired by Date Range and Classification

```{r}
artworks_subset <- artworks %>% 
 filter(!is.na(artist)) %>% 
 filter(date_acquired >= '2010-01-01') %>% 
 filter(date_acquired <= '2020-01-01') %>% 
 filter(classification == 'Painting')

artworks_subset
```

### Top 10 Artists by Classification

```{r}
artworks_subset %>% 
 count(artist, sort = TRUE) %>%
 mutate(artist = forcats::fct_reorder(artist, n)) %>% 
 head(10) %>% 
 ggplot(aes(x = artist, y = n)) +
 geom_col() +
 coord_flip()  
```

### Distribution of Heights and Widths by Classification

```{r}
artworks_subset %>% 
  ggplot(aes(x = width_cm, y = height_cm)) +
  geom_point(alpha = 0.5) +
  labs(
    x = 'Width',
    y = 'Height'
  )
```
### Distribution of Heights and Widths by Classification: Rectangle Plot

```{r}
artworks_subset %>% 
  ggplot(aes(xmin = 0, ymin = 0, xmax = width_cm, ymax = height_cm)) +
  geom_rect(alpha = 0.5) +
  labs(
    title = 'Distribution of Width vs. Height',
    subtitle = 'Classification: Painting',
    x = 'Width',
    y = 'Height'
  )
```
